version: '3.7'

services:

  frontend:
    image: node:20
    container_name: frontend
    volumes:
      - ./:/var/www/html
    entrypoint: ['npm', '--no-bin-links']
    networks:
      - laravel

  backend:

    build:
      context: .
      target: php
      args:
        - APP_ENV=${APP_ENV}

    environment:
      - APP_ENV=${APP_ENV}
      - CONTAINER_ROLE=app

    depends_on:
      - db

    volumes:
      - ./:/var/www/html

    ports:
      - 8000:8000
      - 443:443

    networks:
      - laravel

  db:
    image: mysql:8.3

    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=1

    volumes:
      - app-data:/var/lib/mysql

    ports:
      - 3306:3306

    networks:
      - laravel

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   depends_on:
  #     - db
  #   ports:
  #     - 8080:80
  #   environment:
  #     - PMA_HOST=db
  #     - PMA_PORT=3306

volumes:
  app-data: {}

networks:
  laravel:
